version: '3.9'

services:
  #############
  #    API    #
  #############
  api1: &api
    image: leandronsp/rinha-backend-ruby
    container_name: api1
    environment:
      - RUBY_YJIT_ENABLE=1
      - DB_POOL_SIZE=5
        #- WEB_CONCURRENCY=4
        #- PGBOUNCER_ENABLED=1
        #- PROFILE_QUERIES=true
    command: rackup
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2: 
    <<: *api
    container_name: api2

  #############
  #    DB     #
  #############
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

  pgbouncer:
    image: pgbouncer/pgbouncer
    container_name: pgbouncer
    environment:
      - DATABASES_HOST=postgres
      - DATABASES_PORT=5432
      - DATABASES_USER=postgres
      - DATABASES_PASSWORD=postgres
      - DATABASES_DBNAME=postgres
      - DATABASES_POOL_SIZE=50
      - PGBOUNCER_MAX_CLIENT_CONN=50

  #############
  #   PROXY   #
  #############
  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

volumes:
  rubygems:
